## Numpy

### Convention for importing Array

In [ ]:
import numpy as np

In [ ]:
ar=[1,2,3,4]
print(type(ar))

<class 'list'>


In [ ]:
a = np.array(ar)
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(4,)


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.ndim)
print(b.shape)

2
(2, 3)


### Inbuilt functions to Initialize array

In [ ]:
n1= np.random.random((2,3))
n1

array([[0.95423275, 0.01540669, 0.45523604],
       [0.4391904 , 0.17332178, 0.71157252]])

In [ ]:
n2=np.zeros((2,3))
n2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
n3=np.ones((2,3))
n3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
n4=np.identity(3)
n4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Operations on array

In [ ]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[1,2,3],[4,5,6]])

In [ ]:
c+d

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
c*d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
c**2

array([[ 1,  4,  9],
       [16, 25, 36]])

### Indexing with array and Using arrays for data preprocessing

In [ ]:
e=[11,12,13,14,15,16,17,18,19,20]
e = np.array(e)

In [ ]:
print(e[0])
e[3]

11


14

In [ ]:
d[1,0:2]

array([4, 5])

In [ ]:
g= np.array([[11,12,13],[14,15,16],[17,18,19]])

In [ ]:
g[:3,:2]

array([[11, 12],
       [14, 15],
       [17, 18]])

In [ ]:
g[g>15]

array([16, 17, 18, 19])

### Pandas

In [ ]:
import pandas as pd

In [ ]:
days=pd.Series(['Monday','Tuesday','Wednesday'])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [ ]:
days_list=np.array(['Monday','Tuesday','Wednesday'])
numpy_days=pd.Series(days_list)
print(numpy_days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [ ]:
days=pd.Series(['Monday','Tuesday','Wednesday'],index=['a','b','c'])
days

a       Monday
b      Tuesday
c    Wednesday
dtype: object

In [ ]:
days[0]

'Monday'

In [ ]:
days[1:]

b      Tuesday
c    Wednesday
dtype: object

In [ ]:
df_dict={'Country':['Ghana','Kenya','Nigeria','Togo'],
         'Capital':['Accra','Nairobi','Abuja','Lome'],
         'Population':[10000,8500,35000,1200],
         'Age':[60,70,80,75]}

In [ ]:
df=pd.DataFrame(df_dict,index=[2,4,6,8])
df_list=[
    ['Ghana','Accra',10000,60],
    ['Kenya','Nairobi',8500,70],
    ['Nigeria','Abuja',35000,80],
    ['Togo','Lome',12000,75]

]

In [ ]:
df1=pd.DataFrame(df_list,columns=['Country','Capital','Population','Age'],
                 index=[2,4,6,8])
df1

Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75

In [ ]:
df1.iloc[3]

Country        Togo
Capital        Lome
Population    12000
Age              75
Name: 8, dtype: object

In [ ]:
df1['Capital']

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: Capital, dtype: object

In [ ]:
df1.describe()

Population        Age
count      4.000000   4.000000
mean   16375.000000  71.250000
std    12499.166639   8.539126
min     8500.000000  60.000000
25%     9625.000000  67.500000
50%    11000.000000  72.500000
75%    17750.000000  76.250000
max    35000.000000  80.000000